SanFu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='sanfu'))
]

app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^index/$',views.index,name='index' ),#首页

    url(r'^login/$',views.login,name='login'),#登录
    url(r'^logout/$',views.logout,name='logout'),#退出
    url(r'^regiest/$',views.regiest,name='regiest'),#注册
    url(r'^checkemail/$',views.checkemail,name='checkemail'),#验证账号

    url(r'^goodsList/$',views.goodsList,name='goodsList'),#商品列表
    url(r'^goodsMsg/(\d+)/$',views.goodsMsg,name='goodsMsg'),#商品详情

    url(r'^cart/$',views.cart,name='cart' ),#购物车
    url(r'^addcart/$',views.addcart,name='addcart' ),#添加购物车
    url(r'^chekall/$',views.chekall,name='chekall'),
    url(r'^order/$',views.order,name='order'),
    url(r'orderlist/$', views.orderlist, name='orderlist'),

    url(r'^returnurl/$', views.returnurl, name='returnurl'),    # 支付成功后，客户端的显示
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'), # 支付成功后，订单的处理
    url(r'^pay/$', views.pay, name='pay'),  # 支付

]

app/models.py
from django.db import models

# Create your models here.
#轮播图
class Wheel(models.Model):
    img = models.CharField(max_length=300) #图片地址

    class Meta:
        db_table = 'sf_wheel'

#导航标志图
class BannerUrl(models.Model):
    img = models.CharField(max_length=300) #图片地址
    categoryid = models.CharField(max_length=100)  # 分类id
    class Meta:
        db_table = 'sf_bannerurl'

#商品
class Goods(models.Model):
    img = models.CharField(max_length=300) #图片地址
    name = models.CharField(max_length=300) #图片名
    truckid = models.CharField(max_length=100)  # 商品id
    original = models.DecimalField(max_digits=5, decimal_places=1) #原价
    present = models.DecimalField(max_digits=5, decimal_places=1) #现价
    categoryid = models.CharField(max_length=100) #分类id
    childid = models.CharField(max_length=100) #子类id
    childname = models.CharField(max_length=200) #子类名称
    dealerid  = models.CharField(max_length=100) #详情页id
    hot = models.IntegerField() #是否热卖
    new = models.IntegerField() #是否新品
    class Meta:
        db_table = 'sf_goods'

class User(models.Model):
    # 邮箱
    email = models.CharField(max_length=40, unique=True)
    # 密码
    password = models.CharField(max_length=256)
    # 昵称
    name = models.CharField(max_length=100)
    class Meta:
        db_table = 'sf_user'

class Car(models.Model):
    # 用户信息
    user = models.ForeignKey(User)
    # 商品信息
    goods = models.ForeignKey(Goods)
    #商品数量
    number = models.IntegerField()
    #是否选择
    isselect = models.BooleanField(default=True)
    #是否删除
    isdelete = models.BooleanField(default=False)
    class Meta:
        db_table = 'sf_car'

# 订单
class Order(models.Model):
    user = models.ForeignKey(User)
    # 创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    # 更新时间
    updatetime = models.DateTimeField(auto_now=True)
    # 状态
    # -1 过期
    # 0 未付款
    # 1 已付款，待发货
    # 2 已发货，待收货
    # 3 已收货，待评价
    # 4 已评价
    status = models.IntegerField(default=0)
    # 订单号
    identifier = models.CharField(max_length=256)



# 订单商品
class OrderGoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(Goods)

    # 商品选择规格
    number = models.IntegerField()

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta accesskey="百货商城 服装 时尚 鞋帽" />
		<meta content="百货商城 服装 时尚 鞋帽" />
		<title>我的购物车</title>
		<link rel='icon' href='{% static 'img/index/icon.ico' %}' type=‘image/x-ico’ />
		<link rel="stylesheet" href="{% static 'css/head.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iconfont.css' %}" />
		<link rel="stylesheet" href="{% static 'css/gradient.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/head.js' %}"></script>
{#         <script type="text/javascript" src="{% static 'js/myhome.js' %}"></script>#}
	</head>

	<body>
        	<!--
        	主head
        -->
		<div class="loginbar">
			<div class="loginbarMain">
				<div>
					<ul>
						<li><a href="#" style="color:red;margin-right:5px"></a>您好，欢迎光临sanfu！</li>
						<li>
							<a href="http://10.2.166.37:8020/sanfu/login.html">登录</a>
						</li>
						<li>
							<a href="#">免费注册</a>
						</li>
						<li>
							<a href="#" style="background: url(/static/img/index/nzzz3.jpg) no-repeat;background-position: left;padding-left: 15px;">收藏三福</a>
						</li>
						<li>网店热线: 400-893-9833</li>
						<li style="border: none;height: auto;position: relative;top: -5px;">
							<a href="#" style="background:url({% static 'img/index/wxjgz.png' %}) no-repeat;width: 65px;height:22px;display: block;"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header" style="height: auto;overflow: hidden;">
			<div class="hearderMain" style="margin-top:20px;">
				<ul>

					<li>
						<img src="{% static 'img/cart/20160917162638_4.jpg'%}" style="width: 972px;height: 99px;position: absolute;top: 40px;">
						<a href="http://10.2.166.37:8020/sanfu/index.html"><img src="{% static 'img/index/std_logo.jpg.png'%}" style="margin-right: 60px;position: relative;z-index: 1;"></a>
					</li>
				</ul>
			</div>
		</div>
		<!--
        	main开始
        -->
        <div class="cartmain">
        	<div class="maintitle">
        		<h4><span class="icon iconfont"></span>我的购物车</h4>
        	</div>
        	<div class="mainbody">
        		<table id="mycart">
        			<tbody><tr>
        				<th><input type="checkbox" id="checkall"  checked="checked">全选</th>
        				<th>图片</th>
        				<th>商品信息</th>
        				<th>促销价</th>
        				<th>数量</th>
        				<th>小计</th>
        				<th>操作</th>
        			</tr></tbody>
                    {% for cart in carts %}
                    <tr class ="shoping">
                        <td><input data-checkid="{{ cart.id}}" type='checkbox' class="childcheck" checked="checked"/></td>
                        <td><img  src="{% static cart.goods.img %}"/></td>
                        <td><span>{{ cart.goods.name }}</span></td>
                        <td class="tdp"><span class="price">{{ cart.goods.original }}</span><span>元</span></td>
                        <td class="tdp"><button class='sub' data-cartid="{{ cart.id}}">-</button>
                            <input class="numb" type='text' value='{{ cart.number}}'/>
                            <span></span>
                            <button class='add' data-cartid="{{ cart.id}}">+</button></td>
                        <td class="tdp"><span>￥</span><span class="mprice"></span><span>元</span></td>
                        <td><a class='delethis'>删除商品</a></td>
                    </tr>
                    {% endfor %}
        		    <tr id="noneshop"><td colspan="7">购物车中没有商品记录！</td></tr></tbody>
                </table>
        		<div class="cartDele">
        			<button id="deleteGoods"><i class="icon iconfont"></i>删除选中的商品</button><span>商品数量总计：<b>0</b></span>
        		</div>
        		<div class="cartToal">
        			<span>商品总价(不含运费)：￥<b>0.00</b>元</span>
        		</div>
        		<div class="cartBtn">
                    <input type="button" value="继续购物" style="background: #ababab;" id="turnBackList"><a href="{% url 'sanfu:order' %}"  style="background: #d90349;" id="payoder">去结算</a>
        		</div>
        	</div>
        </div>
        <!--
        	main结束
        -->
		<!--
			主footer开始
        -->
				<div style="width: 100%;height: auto;overflow: hidden;" class="gradient">

					<div class="ftService">
						<ul>
							<li><img src="{% static 'img/index/zpbz.png'%}">
								<div>
									<h2>正品保障</h2><span>三福官方品牌</span></div>
							</li>
							<li><img src="{% static 'img/index/mzgx.png'%}">
								<div>
									<h2>50款</h2><span>每周更新</span></div>
							</li>
							<li><img src="{% static 'img/index/wlyth.png'%}">
								<div>
									<h2>15天</h2><span>无理由退货</span></div>
							</li>
							<li><img src="{% static 'img/index/hyfw.png'%}">
								<div>
									<h2>会员服务</h2><span>门店热线：<b>400-1601-606</b></span><span>网店热线：<b>400-8939-833</b></span></div>
							</li>
							<li style="border: none;"><i>银联特约商户</i></li>
						</ul>
					</div>
					<div class="ftNav">
						<ul class="ftNavTitle">
							<li><label style="background: url({% static 'img/index/xszn.png' %}) no-repeat left;padding-left: 30px;">新手指南</label></li>
							<li><label style="background: url({% static 'img/index/fkfs.png' %}) no-repeat left;padding-left: 35px;">付款方式</label></li>
							<li><label style="background: url({% static 'img/index/psfs.png' %}) no-repeat left;padding-left: 30px;">配送方式</label></li>
							<li><label style="background: url({% static 'img/index/shfw.png' %}) no-repeat left;padding-left: 30px;">售后服务</label></li>
							<li><label style="background: url({% static 'img/index/bzzx.png' %}) no-repeat left;padding-left: 30px;">帮助中心</label></li>
							<li><label style="background: url({% static 'img/index/gywm.png' %}) no-repeat left;padding-left: 30px;">关于我们</label></li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">新用户注册</a>
							</li>
							<li>
								<a href="#">找回密码</a>
							</li>
							<li>
								<a href="#">用户协议</a>
							</li>
							<li>
								<a href="#">会员规则</a>
							</li>
							<li>
								<a href="#">积分说明</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">购物流程</a>
							</li>
							<li>
								<a href="#">订单状态</a>
							</li>
							<li>
								<a href="#">优惠劵使用</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">购衣常识</a>
							</li>
							<li>
								<a href="#">发票制度</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">配送方式</a>
							</li>
							<li>
								<a href="#">支付方式</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">退换货政策</a>
							</li>
							<li>
								<a href="#">退货办理流程</a>
							</li>
							<li>
								<a href="#">线上退货流程</a>
							</li>
							<li>
								<a href="#">线下退货流程</a>
							</li>
							<li>
								<a href="#">退款说明</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">三福招聘</a>
							</li>
							<li>
								<a href="#">关于三福</a>
							</li>
							<li>
								<a href="#">官方微博</a>
							</li>
							<li>
								<a href="#">快递查询</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="copyright">
					<p>粤ICP备15015680号 © 2011 SanFu All Rights Reserved.广东三福服装有限公司,禁止非法复制,
						<a href="http://www.miit.gov.cn/">工信部备案查询</a>
						<a href="http://webscan.360.cn/index/checkwebsite/url/sanfu.com"><img src="{% static 'img/index/360safe.png'%}" style="position: relative;top: 10px;"></a>
					</p>
				</div>
				<!--
			主footer结束
        -->
    </body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title>用户登录</title>
		<meta accesskey="百货商城 服装 时尚 鞋帽" />
		<meta content="百货商城 服装 时尚 鞋帽" />
		<link rel='icon' href='{% static 'img/index/icon.ico' %}' type=‘image/x-ico’ />
		<link rel="stylesheet" href="{% static 'css/head.css' %}" />
		<link rel="stylesheet" href="{% static 'css/login.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/login.js' %}" ></script>
{#        <script type="text/javascript" src="{% static 'js/myhome.js' %}"></script>#}
	</head>

	<body>


		<!--
        	主head
        -->
		<div class="loginbar">
			<div class="loginbarMain">
				<div>
					<ul>
						<li>您好，欢迎光临sanfu！</li>
						<li>
                            {% if user %}
							    <a href="#">{{ user.name }}</a>
                            {% else %}
                                <a id="login-i">登录</a>
                            {% endif %}
						</li>
						<li>
                            {% if user %}
							    <a href="{% url 'sanfu:logout' %}">退出</a>
                            {% else %}
                                <a id="register-li">免费注册</a>
                            {% endif %}

						</li>
						<li>
							<a href="#" style="background: url({% static 'img/index/nzzz3.jpg' %}) no-repeat;background-position: left;padding-left: 15px;">收藏三福</a>
						</li>
						<li>网店热线: 400-893-9833</li>
						<li style="border: none;height: auto;position: relative;top: -5px;">
							<a href="#" style="background:url({% static 'img/index/wxjgz.png' %}) no-repeat;width: 65px;height:22px;display: block;"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header" style="height: auto;overflow: hidden;">
			<div class="hearderMain" style="margin-top:20px;">
				<ul>
					<li>
						<a href="http://10.2.166.37:8000/index.html"><img src="{% static 'img/index/std_logo.jpg.png'%}" style="margin-right: 60px;"></a>
					</li>
			</ul></div>
			<div class="loginMain">
				<div class="loginAd">
					<img src="{% static 'img/login/20160913155214_4.jpg'%}">
				</div>
				<div class="loginWay">
					<div>
						<ul class="logintab">
							<li>微信扫码登录
							</li>
							<li  class="loginliact">帐号登录</li>
						</ul>
					</div>
					<div class="qrLogin">
						<img src="{% static 'img/login/20160913155214_1.png'%}">
					</div>
					<div class="formLogin">
						<ul>
							<form action="{% url 'sanfu:login' %}" method="post">
                                {% csrf_token %}
                                <li><i style="color:red;font-size:10px;">{{ ps_err }}</i></li>
                                <li><i style="color:red;font-size:10px;">{{ user_err }}</i></li>
							    <li><input type="text" placeholder="请输入卡号/手机号" id="userName" name="loginName"></li>
							    <li><input type="password" placeholder="请输入密码" id="passWord" name="loginPwd"></li>
							    <li><input type="checkbox" value="1" id="remenberMsg"><label>记住用户名</label><span id="loginerror"></span></li>
                                <li><input type="submit" value="登录" id="loginBtn" style="background-color: #00adef;width: 10rem;"></li>

                                <li><div><a href="#">忘记密码？</a> | <a href="#">注册帐号</a></div></li>
                            </form>
						</ul>
					</div>
					<div class="loginFriend">
						<span>合作网站帐号登录：</span>
						<a href="#"></a>
					</div>
				</div>

			</div>
		</div>
		<!--
        	footer
        -->
		<div class="loginFooter">
			<ul>
				<li><a href="#">关于三福</a></li>
				<li><a href="#">帮助中心</a></li>
				<li><a href="#">联系我们</a></li>
				<li><a href="#">天猫商城</a></li>
				<li><a href="#">官方微博</a></li>
			</ul>
			<p>粤ICP备1501568(1/3)号 © 2011 SanFu All Rights Reserved.广东省三福百货有限公司,禁止非法复制,<a href="#">工信部备案查询</a></p>
		</div>
    </body>
</html>

templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/orderdetail.js' %}"></script>
</head>
<body>
    <div class="orderdetail">
        <p>
            订单号: {{ order.identifier }}
        </p>
        <ul>
            {% for ordergoods in order.ordergoods_set.all %}
            <li>
                <span>{{ ordergoods.goods.productlongname }}</span>
                &nbsp;
                <i>x{{ ordergoods.number }}</i>
            </li>
            {% endfor %}
        </ul>

        <button class="btn btn-default" id="alipay" data-orderid="{{ order.id }}">支付</button>
    </div>
</body>
</html>

templates/orderlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
</head>
<body>
        <div class="orderlist">
        {% for order in orders %}
            <p class="bg-info">
                <a href="{% url 'sanfu:order' order.identifier %}">
                    订单号: {{ order.identifier }} --
                    {% if order.status == 0 %}
                        未付款
                    {% elif order.status == 1 %}
                        待发货
                    {% elif order.status == 2 %}
                        待收货
                    {% elif order.status == 3 %}
                        待评价
                    {% elif order.status == 4 %}
                        已评价
                    {% endif %}
                </a>
            </p>
            <br>
        {% endfor %}
    </div>
</body>
</html>

templates/regiest.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta accesskey="百货商城 服装 时尚 鞋帽" />
		<meta content="百货商城 服装 时尚 鞋帽" />
		<title>注册界面</title>
		<link rel='icon' href='{% static 'img/index/icon.ico' %}' type=‘image/x-ico’ />
		<link rel="stylesheet" href="{% static 'css/head.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iconfont.css' %}" />
		<link rel="stylesheet" href="{% static 'css/gradient.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/regiest.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/head.js' %}"></script>
{#        <script type="text/javascript" src="{% static 'js/myhome.js' %}"></script>#}
	</head>

	<body>

		<!--
        	主head
        -->
		<div class="loginbar">
			<div class="loginbarMain">
				<div>
					<ul>
						<li><a href="#" style="color:red;margin-right:5px"></a>您好，欢迎光临sanfu！</li>
						<li>
							<a href="http://10.2.166.37:8000/login.html">{{ user.name | default:'未登录' }}</a>
						</li>
						<li>
							<a href="http://10.2.166.37:8000/regiest.html">免费注册</a>
						</li>
						<li>
							<a href="#" style="background: url(/static/img/index/nzzz3.jpg) no-repeat;background-position: left;padding-left: 15px;">收藏三福</a>
						</li>
						<li>网店热线: 400-893-9833</li>
						<li style="border: none;height: auto;position: relative;top: -5px;">
							<a href="#" style="background:url(/static/img/index/wxjgz.png) no-repeat;width: 65px;height:22px;display: block;"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header" style="height: auto;overflow: hidden;">
			<div class="hearderMain" style="margin-top:20px;">
				<ul>
					<li>
						<a href="http://10.2.166.37:8000/index.html"><img src="{% static 'img/index/std_logo.jpg.png'%}" style="margin-right: 60px;"></a>
					</li>
					<li>
						<label style="line-height: 80px;font-weight: bold;color:#00ADEF;font-size: 24px;margin-left:400px ;"><span class="icon iconfont" style="font-size: 24px;"> </span>400-893-9833</label>
					</li>
				</ul>
			</div>
			<hr color="#00ADEF">
		</div>
		<!--
        	main
        -->

        <div>
        	<div class="regMain">
        		<div class="regForm">
        			<div style="border-bottom: 2px solid #eee;margin-bottom: 20px;">
        				<h3><span class="icon iconfont"></span> 注册会员 REGISTRATION</h3>
        			</div>
                    <form action="{% url 'sanfu:regiest' %}" method="post">
                         {% csrf_token %}
                        <div class="checkname">
                            <label>昵称</label>
                            <input id="uername" type="text" placeholder="请输入昵称" name="uername">
                            <i></i>
                        </div>
        			    <div class="checkemail">
                            <label>账号</label>
                            <input id="email" type="text" placeholder="邮箱/用户名/手机号" name="email">
                            <i></i>
                        </div>
        			    <div class="checkpwd">
                            <label>密码</label>
                            <input id="pwd" type="password" placeholder="请输入5~16位密码" name="password">
                            <i></i>
                        </div>
        			    <div class="repwd">
                            <label>确认密码</label>
                            <input id="repwd" type="password" placeholder="">
                            <i></i>
                        </div>


        			    <div ><input id="protocol" type="checkbox" name="protocol"><label style="width: 250px;font-size: 12px;">我已阅读并同意<a href="#">《三福用户注册协议》</a></label></div>
        			    <div ><input id="register" type="button" value="注册"></div>
                    </form>
                </div>
        		<div class="regAd">
        			<label>已有三福账号？&nbsp;</label><a href="{% url 'sanfu:login' %}">登录</a>
        		</div>
        	</div>
        </div>

		<!--
			主footer开始
        -->
		<div style="width: 100%;height: auto;overflow: hidden;" class="gradient">

			<div class="ftService">
				<ul>
					<li><img src="{% static 'img/index/zpbz.png'%}">
						<div>
							<h2>正品保障</h2><span>三福官方品牌</span></div>
					</li>
					<li><img src="{% static 'img/index/mzgx.png'%}">
						<div>
							<h2>50款</h2><span>每周更新</span></div>
					</li>
					<li><img src="{% static 'img/index/wlyth.png'%}">
						<div>
							<h2>15天</h2><span>无理由退货</span></div>
					</li>
					<li><img src="{% static 'img/index/hyfw.png'%}">
						<div>
							<h2>会员服务</h2><span>门店热线：<b>400-1601-606</b></span><span>网店热线：<b>400-8939-833</b></span></div>
					</li>
					<li style="border: none;"><i>银联特约商户</i></li>
				</ul>
			</div>
		</div>
		<div class="copyright">
			<p>粤ICP备15015680号 © 2011 SanFu All Rights Reserved.广东三福服装有限公司,禁止非法复制,
				<a href="http://www.miit.gov.cn/">工信部备案查询</a>
				<a href="http://webscan.360.cn/index/checkwebsite/url/sanfu.com"><img src="{% static 'img/index/360safe.png'%}" style="position: relative;top: 10px;"></a>
			</p>
		</div>
		<!--
			主footer结束
        -->
    </body>

</html>